services:
  # first service - mongo 
  mongo:
    container_name: mongo
    image: mongo:latest

    # storage to persist data in my hard disk
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"

  bu-fsd-node:
    container_name: bu-fsd-node
    build: .

    # the app will start only after mongo starts
    depends_on:
      - mongo

    ports:
      - "${PORT}:${PORT}"

    # environment variables
    environment:
      - PORT=${PORT}
      - MONGO_URL=${MONGO_URL}

# storage to persist data in my hard disk
volumes:
  db-data:
